const tg=window.Telegram.WebApp;tg.expand();tg.ready();tg.setHeaderColor('#0a0a0a');tg.setBackgroundColor('#0a0a0a');
const state={user:{id:tg.initDataUnsafe.user?.id||0,username:tg.initDataUnsafe.user?.username||'guest'},charts:{}};
const mockData={stats:{totalEarned:1250000,totalDeals:47,rank:'ELITE',nextRank:'MASTER',progress:75,currentProgress:35,nextRequired:50,streak:12,daysInTeam:145,globalRank:8,refIncome:45000,refCount:12,refActive:5},activity:{daily:[15,22,18,35,28,42,31],labels:['Пн','Вт','Ср','Чт','Пт','Сб','Вс']},achievements:[{id:1,icon:'🏆',name:'Первый профит',unlocked:true},{id:2,icon:'🔥',name:'Серия 7 дней',unlocked:true},{id:3,icon:'💎',name:'Топ 10',unlocked:true},{id:4,icon:'🚀',name:'50 сделок',unlocked:false}],top:[{rank:1,name:'@crypto_king',profits:156,sum:4500000},{rank:2,name:'@dark_matter',profits:134,sum:3800000},{rank:8,name:'@'+state.user.username,profits:47,sum:1250000,isMe:true}]};
document.addEventListener('DOMContentLoaded',()=>{setTimeout(()=>{document.getElementById('loader').style.opacity='0';setTimeout(()=>{document.getElementById('loader').style.display='none';document.getElementById('mainContent').style.display='block';initApp()},500)},1500)});
function initApp(){loadUserData();initCharts();renderAchievements();renderTop();updateStreakTimer();setInterval(()=>{document.querySelector('.online-count').textContent=(Math.floor(Math.random()*20)+10)+' online'},5000)}
function loadUserData(){const s=mockData.stats;animateValue('totalEarned',0,s.totalEarned,1500,true);animateValue('totalDeals',0,s.totalDeals,1000);document.getElementById('username').textContent='@'+state.user.username;document.getElementById('userId').textContent='ID: '+state.user.id;document.getElementById('rankFlair').textContent=s.rank;document.getElementById('daysInTeam').textContent=s.daysInTeam+' дней';document.getElementById('globalRank').textContent='#'+s.globalRank;document.getElementById('progressPercent').textContent=s.progress+'%';document.getElementById('rankProgress').style.width=s.progress+'%';document.getElementById('currentProgress').textContent=s.currentProgress+' / '+s.nextRequired;document.getElementById('nextRankName').textContent=s.nextRank;if(s.streak>0){document.getElementById('streakBanner').style.display='flex';document.getElementById('streakCount').textContent=s.streak+' DAYS'}document.getElementById('refIncome').textContent=s.refIncome.toLocaleString()+' ₽';document.getElementById('refCount').textContent=s.refCount;document.getElementById('refActive').textContent=s.refActive;document.getElementById('refLink').textContent='https://t.me/shutter_bot?start=ref'+state.user.id}
function animateValue(id,start,end,duration,isCurrency=false){const obj=document.getElementById(id);const range=end-start;const stepTime=Math.max(Math.abs(Math.floor(duration/range)),50);let current=start;const timer=setInterval(()=>{current+=Math.ceil(range/(duration/stepTime));if(current>=end)current=end;obj.textContent=isCurrency?current.toLocaleString():current;if(current==end)clearInterval(timer)},stepTime)}
function initCharts(){const ctx1=document.getElementById('activityChart')?.getContext('2d');if(ctx1){state.charts.activity=new Chart(ctx1,{type:'line',data:{labels:mockData.activity.labels,datasets:[{label:'Профиты',data:mockData.activity.daily,borderColor:'#ff6b00',backgroundColor:'rgba(255,107,0,0.1)',borderWidth:3,tension:0.4,fill:true}]},options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{display:false}},scales:{y:{beginAtZero:true,grid:{color:'rgba(255,255,255,0.05)'},ticks:{color:'#888',callback:v=>(v/1000)+'k'}},x:{grid:{display:false},ticks:{color:'#888'}}}}}))}}
function renderAchievements(){const grid=document.getElementById('achievementsGrid');grid.innerHTML=mockData.achievements.map(a=>`<div class="achievement ${a.unlocked?'unlocked':''}"><div style="font-size:28px;filter:${a.unlocked?'grayscale(0%)':'grayscale(100%)'};opacity:${a.unlocked?1:0.5}">${a.icon}</div><div style="font-size:10px;text-align:center;color:var(--text-secondary)">${a.name}</div></div>`).join('')}
function renderTop(){const list=document.getElementById('topList');list.innerHTML=mockData.top.map(t=>{const rankClass=t.rank===1?'gold':'';const meStyle=t.isMe?'style="border-color:var(--accent);background:rgba(255,107,0,0.1)"':'';return`<div class="top-item" ${meStyle}><div class="top-rank ${rankClass}">${t.rank}</div><div style="flex:1"><div style="font-weight:700">${t.name}${t.isMe?' (ты)':''}</div><div style="font-size:12px;color:var(--text-secondary)">${t.profits} профитов</div></div><div style="font-weight:800;color:var(--success)">${(t.sum/1000000).toFixed(1)}M ₽</div></div>`}).join('')}
function switchTab(tab){document.querySelectorAll('.tab-content').forEach(t=>t.classList.remove('active'));document.querySelectorAll('.tab-btn').forEach(b=>b.classList.remove('active'));document.getElementById(tab+'-tab').classList.add('active');document.querySelector(`[data-tab="${tab}"]`).classList.add('active');tg.HapticFeedback.impactOccurred('light')}
function copyRef(){const link=document.getElementById('refLink').textContent;navigator.clipboard.writeText(link).then(()=>{showToast('Успешно','Ссылка скопирована');tg.HapticFeedback.notificationOccurred('success')})}
function showToast(title,message){const toast=document.getElementById('toast');toast.querySelector('.toast-title').textContent=title;toast.querySelector('.toast-message').textContent=message;toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),3000)}
function updateStreakTimer(){const timerEl=document.getElementById('streakTimer');if(!timerEl)return;setInterval(()=>{const now=new Date();const midnight=new Date();midnight.setHours(24,0,0,0);const diff=midnight-now;const h=Math.floor(diff/3600000);const m=Math.floor((diff%3600000)/60000);const s=Math.floor((diff%60000)/1000);timerEl.textContent=`${String(h).padStart(2,'0')}:${String(m).padStart(2,'0')}:${String(s).padStart(2,'0')}`},1000)}
function quickAction(){tg.showPopup({title:'Быстрое действие',message:'Что хочешь сделать?',buttons:[{id:'profit',type:'default',text:'💰 Слить профит'},{id:'support',type:'default',text:'📞 Поддержка'},{type:'cancel'}]})}
function toggleTheme(){const html=document.documentElement;const current=html.getAttribute('data-theme');const next=current==='dark'?'light':'dark';html.setAttribute('data-theme',next);localStorage.setItem('theme',next)}
function refreshData(){tg.HapticFeedback.impactOccurred('medium');showToast('Обновлено','Данные синхронизированы')}